apiVersion: ops.csas.cz/v1alpha1
kind: Application
metadata:
  name: madoc
spec:
  source:
    repoURL: https://github.com/tomasdedic/ocpdocCD.git 
    targetRevision: master
    path: ./deploy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
