apiVersion: v1
kind: Route
metadata:
  labels:
    project: hugodoc
  name: proxy
  namespace: blaster
spec:
  host: hdoc.apps.oshi43.csas.elostech.cz
  tls:
    termination: Reencrypt
  to:
    kind: Service
    name: proxy
