apiVersion: apps/v1
kind: Deployment
metadata:
  name: hugodoc
  namespace: blaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pages
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pages
    spec:
      containers:
        - name: www
          image: ghcr.io/tomasdedic/ocpdoc/hugogen:sha-3a162b4a
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
      imagePullSecrets:
        - name: gcr-pull
