apiVersion: apps/v1
kind: Deployment
metadata:
  name: hugodoc
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pages
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pages
    spec:
      containers:
        image: ghcr.io/tomasdedic/ocpdoc/hugogen:sha-95013a9b
      imagePullSecrets:
        - name: gcr-pull
