creation_rules:
        - azure_keyvault: 'https://vaultenc.vault.azure.net/keys/k8secrets/5e402cff4ee6450fa4fac71a9a6b161f'
          #encrypted_regex: "^(objstoreConfi.*)$"
          encrypted_regex: '^(pass.*|.*[Bb]earer.*|.*[Kk]ey|.*[Kk]eys|salt|sentry.*|.*[Tt]oken|.dockerconfigjson)$'
